---
title: "Sue's Version"
output:
  html_document: default
  pdf_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(ggspatial)
library(ggthemes)
library(ggsn)
```
```{r}
policestation <-st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/e5a0066d38ac4e2abbc7918197a4f6af_6.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D", quiet = TRUE)
precincts <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
publicspace <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/2868d370c55d4d458d4ae2224ef8cddd_7.kml")
```
Plot 1

```{r}
ggplot(precincts) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "osm")  +
  geom_sf(color = "lightgreen", size = 0.05, 
          aes(fill = "Precincts")) +
  geom_sf(data = publicspace, size = 0.8, shape = 16, alpha = 0.5, 
          aes(color = "Public Space")) + 
  geom_sf(data= policestation, size= 0.01, shape = 4, 
          aes(color = "Police Stations")) 
```
Plot 2

```{r}
ggplot(precincts) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight")  +
  geom_sf(color = "blue", size = 0.05, 
          aes(fill = "Precincts")) +
  geom_sf(data = publicspace, color = "lightgreen", alpha = 0.5, 
          aes(fill = "Public Space")) + 
  geom_sf(data= policestation, size= 0.02, shape = 16, 
          aes(color = "Police Stations")) 
```

Plot 3

```{r}
ggplot(precincts) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw")  +
  geom_sf(color = NA, size = 0.05, aes(fill = "Precincts")) +
  geom_sf(data = publicspace, color = NA, size = 0.05, alpha = 1, 
          aes(fill = "Public Space")) + 
  geom_sf(data= policestation, size= 1, shape = 16, 
          aes(color = "Police Stations")) +  
  scale_fill_manual(values = c("lightblue", "lightgreen"), name = "fill")
```

Plot 4

```{r}
ggplot(precincts) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartodark")  +
  geom_sf(fill = NA, color = "white", size = 0.05,
          aes(color = "Precincts")) +
  geom_sf(data = publicspace, fill = "grey", color = NA, size = 0.05, alpha = 1, 
          aes(fill = "Public Space")) + 
  geom_sf(data= policestation, size= 2, shape = 13, 
          aes(color = "Police Stations")) 
```

Plot 5

```{r}
ggplot(precincts) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw")  +
  geom_sf(color = "white", size = 0.05, aes(fill = "Precincts")) +
  geom_sf(data = publicspace, color = NA, size = 0.05, alpha = 1, 
          aes(fill = "Public Space")) + 
  geom_sf(data= policestation, color = "red", size= 2,  
          aes(shape = "Police Stations")) +  
  scale_fill_manual(values = c("blue", "green"), name = "Fill") +
  scale_shape_manual(values = 7, name = "Symbol")
```